"""Add is_blacklisted column to tokens table

Revision ID: 061927bd27bb
Revises: 91f996897159
Create Date: 2024-12-13 20:17:13.718359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061927bd27bb'
down_revision: Union[str, None] = '91f996897159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_blacklisted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'is_blacklisted')
    # ### end Alembic commands ###
