"""Add changed column in Job History

Revision ID: 5b85eb64394e
Revises: 061927bd27bb
Create Date: 2024-12-13 20:39:59.989607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b85eb64394e'
down_revision: Union[str, None] = '061927bd27bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_histories', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('job_histories', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_histories', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('job_histories', 'description')
    # ### end Alembic commands ###
