"""added unique constraints to role permission

Revision ID: 6bd651ca7d54
Revises: 316526ea65d9
Create Date: 2024-12-07 17:12:03.442073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd651ca7d54'
down_revision: Union[str, None] = '316526ea65d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['user_id', 'role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    # ### end Alembic commands ###
