"""updated job history table

Revision ID: 88aac2ea4e98
Revises: f471f8b3f03c
Create Date: 2024-12-16 02:26:19.724597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88aac2ea4e98'
down_revision: Union[str, None] = 'f471f8b3f03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_histories_is_active'), 'job_histories', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_histories_user_id'), 'job_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_histories_user_id'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_is_active'), table_name='job_histories')
    # ### end Alembic commands ###
