"""added unique constraints to name in role & permission

Revision ID: 91f996897159
Revises: 6bd651ca7d54
Create Date: 2024-12-07 17:20:33.886999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f996897159'
down_revision: Union[str, None] = '6bd651ca7d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_permission_name', 'permissions', ['name'])
    op.create_unique_constraint('uq_role_name', 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_name', 'roles', type_='unique')
    op.drop_constraint('uq_permission_name', 'permissions', type_='unique')
    # ### end Alembic commands ###
