"""Updated job history model

Revision ID: a694b23d20f8
Revises: 18eb764953f5
Create Date: 2024-12-07 16:07:40.952672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a694b23d20f8'
down_revision: Union[str, None] = '18eb764953f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_histories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('job_histories', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_histories', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('job_histories', 'is_active')
    # ### end Alembic commands ###
