"""added refresh token to token

Revision ID: f471f8b3f03c
Revises: 5b85eb64394e
Create Date: 2024-12-14 21:55:15.843899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f471f8b3f03c'
down_revision: Union[str, None] = '5b85eb64394e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('refresh_token', sa.String(), nullable=False))
    op.add_column('tokens', sa.Column('refresh_expires_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'tokens', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='unique')
    op.drop_column('tokens', 'refresh_expires_at')
    op.drop_column('tokens', 'refresh_token')
    # ### end Alembic commands ###
